### ISSUE TITLE
Better script URL attribution for dynamically inserted scripts

### ISSUE THREAD

**Issue by mattzeunert** [w3c/long-animation-frames#25] opened 2024-12-09 17:18 UTC
When a script is inserted with JavaScript the script URL is currently `""`. This often happens with scripts inserted with tools like Google Tag Manager.

Originally [filed a Chrome bug](https://issues.chromium.org/issues/379143313) and was redirected here.

Wondering if anything could be done to improve attribution for these cases so that developers can understand what script is causing delays.

**Comment by tunetheweb** [comment] 2024-12-09 17:27
I think this is a duplicate of #11 isn't it? If so we can close.

**Comment by andydavies** [comment] 2024-12-10 17:58
Yes, AFAIK it is

**Closed** 2024-12-10 17:59 UTC
